### ISSUE TITLE
Error importing one of the internal libs

### ISSUE THREAD

**Issue by darlanalves** [calvinmetcalf/rollup-plugin-node-builtins#5] opened 2016-03-28 01:52 UTC
I can't find a way around this error while bulding with rollup:

```
ERROR: 'import' and 'export' may only appear at the top level (24:0) in [...]/rollup-plugin-node-builtins/src/es6/util.js
```

I'm not sure why it's happening. Pheraphs is due to an `import` statement in the middle of the 'utils.js':

` import inherit from 'inherits'; `

Any ideas? I got a working build by extracting the 'streams' lib from this plugin and putting into a file in my main project files. 

I've been bashing my head on a wall for weeks to get the `stream` module working with rollup. Your plugin just saved me a lot of time on it. Would be great to have your ES6 versions of common modules as separated packages as well, like process-es6 :)

**Comment by calvinmetcalf** [comment] 2016-03-28 12:30
yeah you have to use the master version of commonjs plugin with the ignoreGlobals option

**Comment by piuccio** [comment] 2016-07-15 16:49
I have the same problem with commonjs plugin `3.1.0`

**Comment by N1kto** [comment] 2016-07-21 13:20
+1 here

**Comment by calvinmetcalf** [comment] 2016-07-21 14:36
are you using the ignoreGlobals options ?

**Comment by N1kto** [comment] 2016-07-21 15:11
I am using commonjs plugin of verstion `3.3.0`. Here is `plugins` part of rollup config:
```
plugins: [
    json(),
    babel({
      include: [
        'node_modules/rollup-plugin-node-builtins/**',
        'lib/**'
      ],
      babelrc: false,
      presets: ['react', 'es2015-rollup', 'stage-0']
    }),
    builtins(),
    nodeResolve({
      jsnext: false, // Default: false
      main: true, // Default: true
      skip: [], // Default: []
      browser: true, // Default: false
      extensions: [ '.js', '.json' ], // Default: ['.js']
      preferBuiltins: true // Default: true
    }),
    commonjs({
      include: 'node_modules/**',
      ignoreGlobal: true,
      namedExports: {
        'node_modules/immutable/dist/immutable.js': [
          'Iterable', 'Seq', 'Collection', 'Map', 'OrderedMap', 'List', 'Stack', 'Set',
          'OrderedSet', 'Record', 'Range', 'Repeat', 'is', 'fromJS'
        ],
        'node_modules/esrever/esrever.js': [ 'reverse' ]
      }
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(NODE_ENV),
      'process.browser': JSON.stringify(true)
    })
  ]
```

**Comment by calvinmetcalf** [comment] 2016-07-21 19:39
try moving builtins() to be after commonjs, also try removing `node_modules/rollup-plugin-node-builtins/**` from the babel include

**Comment by N1kto** [comment] 2016-07-21 21:31
did. no effect.

**Comment by N1kto** [comment] 2016-07-21 23:11
OK. it seems that the error goes away if I comment out following lines in `cjs` dist file:
```
libs.set('process', require.resolve('process-es6'));
libs.set('buffer', require.resolve('rollup-plugin-node-globals/dist/buffer'));
libs.set('util', require.resolve(path.join('..', 'src', 'es6', 'util')));
libs.set('sys', libs.get('util'));
libs.set('events', require.resolve(path.join('..', 'src', 'es6', 'events')));
libs.set('stream', require.resolve(path.join('..', 'src', 'es6', 'stream')));
libs.set('path', require.resolve(path.join('..', 'src', 'es6', 'path')));
libs.set('querystring', require.resolve(path.join('..', 'src', 'es6', 'qs')));
```
Not sure about the exact consequences of doing so, I mean maybe there are some negative side effects. But the error is not thrown and final bundle **does** contain node builtins' shims.

Few thoughts on possible root causes of the problem:
- those `es6` modules seem to be extra there since that is a `commonjs` bundle file. I know that they are simple transpiled from `src` file, but at least from `cjs` `dist` file they seem to be extra.
- don't they (those lines) over-write `commonjs` modules from `node-libs-browser` being loaded into the *libs* `Map` few lines earlier?
- The paths to `es6` modules resolve to `es6` files, not `commonjs` ones, so can it be that they are not `babel`ified during compilation?

**Comment by calvinmetcalf** [comment] 2016-07-21 23:33
so I've 'es6' ified some of the browserify core modules so you can do `import {inherits} from 'util'` and have it work, that's what those lines you're commenting out do.  maybe they are getting picked up by bebal try remvoing         'node_modules/rollup-plugin-node-builtins/**',
from the babel config

**Comment by N1kto** [comment] 2016-07-22 08:14
[Did](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/5#issuecomment-234390459). but that doesn't help

**Comment by calvinmetcalf** [comment] 2016-07-22 12:18
so yeah the gist of this is it's a weird interaction between the commonjs module and this one, I think the issue is that [this file](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/b8b8c2b1d5d8b189d168d3050968a3346847faeb/src/es6/util.js) is being incorrectly registered as commonjs

**Comment by N1kto** [comment] 2016-07-22 14:00
I see. 
But I in the context of plugin I still don't get this statement:
> so I've 'es6' ified some of the browserify core modules so you can do import {inherits} from 'util'

I consume the plugin, not its internal stuff, so why would I need to `import {inherits} from 'util'` when using the plugin?

**Comment by pyoner** [comment] 2016-07-23 19:45
How to fix this issuse:
add to commonjs `exclude` "node_modules/rollup-plugin-node-buildins/**"
and add `inherits` lib to deps `npm i inherits --save`

**Comment by calvinmetcalf** [comment] 2016-07-25 11:41
ok looks like I forgot a dep so should be fixed

**Closed** 2016-09-09 00:43 UTC

**Comment by SupremeTechnopriest** [comment] 2016-12-15 19:35
@calvinmetcalf you can use `"jsnext:main"` in `package.json` and then `jsnext: true` in rollup config. https://github.com/rollup/rollup/wiki/jsnext:main

In my opinion its better than excluding manually from `rollup-plugin-commonjs`.

**Comment by calvinmetcalf** [comment] 2016-12-15 19:40
@SupremeTechnopriest I don't think that has anything to do with this current issue which had to do with me forgetting to include a file in my dependencies, feel free to open up a new issue with your particular problem
